# Generated by Django 5.0.6 on 2024-10-03 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='active',
            new_name='is_active',
        ),
    ]
