# Generated by Django 5.0.6 on 2024-10-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_active_cartitem_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='grand_total',
            field=models.IntegerField(default=0),
        ),
    ]
