# Generated by Django 5.0.6 on 2024-09-26 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopingcentre', '0002_remove_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
    ]
